
# OLD syntax for the config
#preload = ~/Pictures/wallpaper/backiee-121292-landscape.jpg
#preload = /home/deepanshu/Pictures/wallpaper/notAxon/Minimalistic/wallpaperflare.com_wallpaper27_1.jpg
#preload = ~/Pictures/wallpaper/backiee-313070-landscape.jpg
#wallpaper = ,/home/deepanshu/Pictures/wallpaper/notAxon/Minimalistic/wallpaperflare.com_wallpaper27_1.jpg



# current syntax for the config
wallpaper {
    monitor = 
    path = /home/deepanshu/Pictures/wallpaper/notAxon/Minimalistic/wallpaperflare.com_wallpaper (27) (1).jpg
    fit_mode = cover
}
splash = false


