#!/usr/bin/bash


#this is script is written to automate the updation of the the homelab config to github

echo "-------------------------------------------------------------------------"
echo "WELCOME TO THE LABPLOAD SCRIPT"
echo ""

set -e
repo_path="$HOME/github_repos/my_repositories/homelab-config/"

#setting up the rsync
echo "Setting up the rsync to backup everything to docs/vaults"
echo ""
rsync -avh --progress --delete "$HOME/homelab_setups/." "$repo_path/current_setup"


echo "" 
echo "All the files have been moved successfully"
echo "Starting git protocols..."
echo ""
echo ""

# if there is a command line argument then the following works
if [ $# -eq 1 ]; then
  cd "$repo_path"
  git add .
  read -p "Please enter you commit message: " message
  git commit -m "$message"
  git push origin main

else
  cd "$repo_path"
  git add .
  git commit -m " $(date) update"
  git push origin main
  
fi

echo "-------------------------------------------------------------------------"




