#!/usr/bin/bash


#!/usr/bin/bash

# Check if no arguments are passed
if [ $# -eq 0 ]; then
  if [ -f ./.venv/bin/activate ]; then
    echo "Activating virtual environment..."
    source ./.venv/bin/activate
  else
    echo "Virtual environment not found at ./.venv/bin/activate"
    exit 1
  fi
else
  echo "This script does not take any arguments. Exiting."
  exit 1
fi

