#!/usr/bin/env bash

# this is a script to automate opening youtube and showing the search results 
# it will work in the format of chromium --new-window --incognito url
# use 'n' for new window and 'i' tag for the icognito mode
# y for youtube

echo "Welcome to the yt-search script."
echo ""

arg1=" "
arg2=" "
arg3="https://www.youtube.com/results?search_query="
search=""

if [ $# -eq 0 ]; then
  read -p "Enter text to be searched on youtube: " search
  chromium https://www.youtube.com/results?search_query="$search"
 
else
  for arg in "$@"
  do 
    if [ "$arg" == "i" ]; then
      arg1="--incognito"

    elif [[ "$arg" == "n" ]]; then
      arg2="--new-window"

    else
      search+="$arg "
    fi 
  done 
  search="${search%" "}"
  search="${search// /+}"
  chromium "$arg1" "$arg2" "$arg3""$search"
  echo "Searching youtube for '$arg3$search'"
fi
