#!/usr/bin/env bash

dotpload
docpload


if [ $# -eq 0 ]; then
dotpload
docpload

else
  if [ "$1" == 'c' ]; then
   dotpload c 
   docpload c

  else
    echo "use argument 'c' to give custom commit messages"
  fi 
fi


