[Legendary]
; Disables the automatic update check
disable_update_check = false
; Disables the notice about an available update on exit
disable_update_notice = false

[Fortnite]
install_tags = ,Startup,FrontEnd,Encrypted,Globals,DefaultGameplayChunk,UnusedOldEarlyStartupPatcherChunk,CosmeticPreInstall,GFP_BaseInstallRoot,GFP_BRCosmetics,GFP_BRCosmeticsInstallOnDemand,GFP_BRCosmeticsInstallOnDemandFat,GFP_CreativeRoot,GFP_BRRoot,GFP_JunoRoot,GFP_DelMarRoot,GFP_Sparks,GFP_BlitzRoot,GFP_StrideMiceRoot,FortniteBR,FNOne,GFP_SaveTheWorldRoot

